# Generated by Django 4.2 on 2024-02-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='liga',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lliga.liga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partido',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partits_local', to='lliga.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partits_visitant', to='lliga.equipo'),
        ),
        migrations.AlterUniqueTogether(
            name='partido',
            unique_together={('local', 'visitante', 'liga')},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.TimeField()),
                ('tipo', models.CharField(choices=[('GOL', 'Gol'), ('AUTOGOL', 'Autogol'), ('FALTA', 'Falta'), ('PENALTY', 'Penalty'), ('MANOS', 'Manos'), ('CESSION', 'Cession'), ('FUERA_DE_JUEGO', 'Fuera De Juego'), ('ASISTENCIA', 'Asistencia'), ('TARGETA_AMARILLA', 'Targeta Amarilla'), ('TARGETA_ROJA', 'Targeta Roja')], max_length=30)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lliga.equipo')),
                ('jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_fets', to='lliga.jugador')),
                ('jugador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_rebuts', to='lliga.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lliga.partido')),
            ],
        ),
        migrations.RemoveField(
            model_name='partido',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='resultado_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='resultado_visitante',
        ),
    ]
